
#ifndef _RSC_TOOL_IMAGE_H_
#define _RSC_TOOL_IMAGE_H_

#define IM_BG_FOCUS_1                                      1 
#define IM_BG_FOCUS_2                                      2 
#define IM_BG_NORMAL_1                                     3 
#define IM_BG_NORMAL_2                                     4 
#define IM_BOX_1                                           5 
#define IM_IC_SET                                          6 
#define IM_IC_SET_EMAIL                                    7 
#define IM_IC_SET_EMAIL_BIG                                8 
#define IM_IC_SET_EMAIL_OPEN                               9 
#define IM_IC_SET_FV_BIG                                  10 
#define IM_IC_SET_LOCK                                    11 
#define IM_IC_SET_LOCK_BIG                                12 
#define IM_IC_SET_MORE                                    13 
#define IM_IC_SET_MORE_BACK                               14 
#define IM_IC_SET_MORE_DUMP                               15 
#define IM_IC_SET_MORE_FAC                                16 
#define IM_IC_SET_MORE_NAME                               17 
#define IM_IC_SET_MORE_RECORD                             18 
#define IM_IC_SET_MUTE_BIG                                19 
#define IM_IC_SET_STOP                                    20 
#define IM_IC_SET_TIME                                    21 
#define IM_IC_SET_TIME_BIG                                22 
#define IM_IC_SET_UNLOCK                                  23 
#define IM_IC_SET_VOICE_BIG                               24 
#define IM_ARROW1_L                                       25 
#define IM_ARROW1_R                                       26 
#define IM_ARROW2_L                                       27 
#define IM_ARROW2_R                                       28 
#define IM_ARROW_L                                        29 
#define IM_ARROW_L_SELECT                                 30 
#define IM_ARROW_R                                        31 
#define IM_ARROW_R_SELECT                                 32 
#define IM_BOX_1_LD                                       33 
#define IM_BOX_1_LT                                       34 
#define IM_BOX_1_MD                                       35 
#define IM_BOX_1_ML                                       36 
#define IM_BOX_1_MM                                       37 
#define IM_BOX_1_MR                                       38 
#define IM_BOX_1_MT                                       39 
#define IM_BOX_1_RD                                       40 
#define IM_BOX_1_RT                                       41 
#define IM_BOX_2_LD                                       42 
#define IM_BOX_2_LT                                       43 
#define IM_BOX_2_MD                                       44 
#define IM_BOX_2_ML                                       45 
#define IM_BOX_2_MM                                       46 
#define IM_BOX_2_MR                                       47 
#define IM_BOX_2_MT                                       48 
#define IM_BOX_2_RD                                       49 
#define IM_BOX_2_RT                                       50 
#define IM_BUTTON_1_L                                     51 
#define IM_BUTTON_1_M                                     52 
#define IM_BUTTON_1_R                                     53 
#define IM_BUTTON_1_SELECT_L                              54 
#define IM_BUTTON_1_SELECT_M                              55 
#define IM_BUTTON_1_SELECT_R                              56 
#define IM_BUTTON_2_L                                     57 
#define IM_BUTTON_2_M                                     58 
#define IM_BUTTON_2_R                                     59 
#define IM_BUTTON_4_L                                     60 
#define IM_BUTTON_4_M                                     61 
#define IM_BUTTON_4_R                                     62 
#define IM_BUTTON_4_SELECT_L                              63 
#define IM_BUTTON_4_SELECT_M                              64 
#define IM_BUTTON_4_SELECT_R                              65 
#define IM_BUTTON_5_L                                     66 
#define IM_BUTTON_5_M                                     67 
#define IM_BUTTON_5_R                                     68 
#define IM_BUTTON_6_BG                                    69 
#define IM_BUTTON_7_M                                     70 
#define IM_BUTTON_7_SELECT_L                              71 
#define IM_BUTTON_7_SELECT_M                              72 
#define IM_BUTTON_7_SELECT_R                              73 
#define IM_CHANGE                                         74 
#define IM_COLORBUTTON_BLUE_SELECT                        75 
#define IM_COLORBUTTON_RED_SELECT                         76 
#define IM_COMM_BOTTOM_LEFT                               77 
#define IM_COMM_BOTTOM_MID                                78 
#define IM_COMM_BOTTOM_RIGHT                              79 
#define IM_COMM_CENTER                                    80 
#define IM_COMM_MID_LEFT                                  81 
#define IM_COMM_MID_RIGHT                                 82 
#define IM_COMM_TOP_LEFT                                  83 
#define IM_COMM_TOP_MID                                   84 
#define IM_COMM_TOP_RIGHT                                 85 
#define IM_CONFIGCONNECT_1                                86 
#define IM_CONFIGCONNECT_2                                87 
#define IM_EPG_COLORBUTTON_YELLOW                         88 
#define IM_GAME_GOBANG_BLACK_1                            89 
#define IM_GAME_GOBANG_WHITE_1                            90 
#define IM_HELP_BLUE                                      91 
#define IM_HELP_EXIT                                      92 
#define IM_HELP_FAV                                       93 
#define IM_HELP_GREEN                                     94 
#define IM_HELP_INFOR                                     95 
#define IM_HELP_MENU                                      96 
#define IM_HELP_OK                                        97 
#define IM_HELP_RECALL                                    98 
#define IM_HELP_RED                                       99 
#define IM_HELP_YELLOW                                   100 
#define IM_ICONS_PAUSE2                                  101 
#define IM_ICON_MUTE                                     102 
#define IM_ICON_PAUSE                                    103 
#define IM_ICON_SOUND                                    104 
#define IM_ICON_SOUND_SCROLL                             105 
#define IM_INFORMATION_FB_2                              106 
#define IM_INFORMATION_FF_2                              107 
#define IM_INFO_ICON_B_1                                 108 
#define IM_INFO_ICON_CW_1                                109 
#define IM_INFO_ICON_SUBTITLE                            110 
#define IM_INFO_ICON_SUBTITLE_2                          111 
#define IM_INFO_ICON_TTX                                 112 
#define IM_INFO_ICON_TTX_2                               113 
#define IM_KEYBOARD_1_L                                  114 
#define IM_KEYBOARD_1_M                                  115 
#define IM_KEYBOARD_1_R                                  116 
#define IM_KEYBOARD_2_L                                  117 
#define IM_KEYBOARD_2_M                                  118 
#define IM_KEYBOARD_2_R                                  119 
#define IM_KEYBOARD_BUTTON_BLANK                         120 
#define IM_KEYBOARD_BUTTON_BLANK_SELECT                  121 
#define IM_KEYBOARD_BUTTON_LEFT                          122 
#define IM_KEYBOARD_BUTTON_LEFT_SELECT                   123 
#define IM_KEYBOARD_BUTTON_RIGHT                         124 
#define IM_KEYBOARD_BUTTON_RIGHT_SELECT                  125 
#define IM_KEYBOARD_INPUTBOX_L                           126 
#define IM_KEYBOARD_INPUTBOX_M                           127 
#define IM_KEYBOARD_INPUTBOX_R                           128 
#define IM_KEYBOARD_NUMBUTTOM_L                          129 
#define IM_KEYBOARD_NUMBUTTOM_M                          130 
#define IM_KEYBOARD_NUMBUTTOM_R                          131 
#define IM_KEYBOARD_NUMBUTTOM_SELECT_L                   132 
#define IM_KEYBOARD_NUMBUTTOM_SELECT_M                   133 
#define IM_KEYBOARD_NUMBUTTOM_SELECT_R                   134 
#define IM_MMENUWIN01_L                                  135 
#define IM_MMENUWIN01_M                                  136 
#define IM_MMENUWIN01_R                                  137 
#define IM_MP3_ICON_BMP                                  138 
#define IM_MP3_ICON_FOLDER                               139 
#define IM_MP3_ICON_GIF                                  140 
#define IM_MP3_ICON_JPG                                  141 
#define IM_MP3_ICON_MP3                                  142 
#define IM_MP3_ICON_PAUSE                                143 
#define IM_MP3_ICON_PAUSE_SELECT                         144 
#define IM_MP3_ICON_PLAY_2                               145 
#define IM_MP3_ICON_PLAY_2_SELECT                        146 
#define IM_MP3_ICON_PNG                                  147 
#define IM_MP3_ICON_STOP                                 148 
#define IM_MP3_ICON_STOP_SELECT                          149 
#define IM_MP3_LOGO_MUSIC_SMALL                          150 
#define IM_M_ICON_3GP                                    151 
#define IM_M_ICON_AVI                                    152 
#define IM_M_ICON_F4V                                    153 
#define IM_M_ICON_FLV                                    154 
#define IM_M_ICON_M2TS                                   155 
#define IM_M_ICON_MKV                                    156 
#define IM_M_ICON_MOV                                    157 
#define IM_M_ICON_MP4                                    158 
#define IM_M_ICON_MPG                                    159 
#define IM_M_ICON_TS                                     160 
#define IM_NET_DISCONNECTED                              161 
#define IM_NET_LINE_CONNECTED                            162 
#define IM_NET_WIFI_CONNECTED                            163 
#define IM_NET_WIFI_DISCONNECTED                         164 
#define IM_PAUSE                                         165 
#define IM_PROGRESS_BG_L                                 166 
#define IM_PROGRESS_BG_M                                 167 
#define IM_PROGRESS_BG_R                                 168 
#define IM_PROGRESS_ICON_PAUSE                           169 
#define IM_PROGRESS_ICON_PLAY                            170 
#define IM_PROGRESS_L                                    171 
#define IM_PROGRESS_M                                    172 
#define IM_PROGRESS_R1                                   173 
#define IM_SATELLITE_LINE_1                              174 
#define IM_SATELLITE_LINE_2                              175 
#define IM_SATELLITE_LINE_3                              176 
#define IM_SATELLITE_LINE_4                              177 
#define IM_SCROLL_BAR                                    178 
#define IM_SCROLL_BAR_BG                                 179 
#define IM_SEARCHBOX_L                                   180 
#define IM_SEARCHBOX_M                                   181 
#define IM_SEARCHBOX_R                                   182 
#define IM_SIGNALBG_L                                    183 
#define IM_SIGNALBG_M                                    184 
#define IM_SIGNALBG_R                                    185 
#define IM_SIGNALSEARCH_BLUE_L                           186 
#define IM_SIGNALSEARCH_BLUE_M                           187 
#define IM_SIGNALSEARCH_BLUE_R                           188 
#define IM_SIGNAL_BLUE_L                                 189 
#define IM_SIGNAL_BLUE_M                                 190 
#define IM_SIGNAL_BLUE_R                                 191 
#define IM_SIGNAL_RED_L                                  192 
#define IM_SIGNAL_RED_M                                  193 
#define IM_SIGNAL_RED_R                                  194 
#define IM_SIGNAL_YELLOW_L                               195 
#define IM_SIGNAL_YELLOW_M                               196 
#define IM_SIGNAL_YELLOW_R                               197 
#define IM_SLISTARROW01_L                                198 
#define IM_SLISTARROW01_R                                199 
#define IM_SLISTARROW02_L                                200 
#define IM_SLISTARROW02_R                                201 
#define IM_SWORD_L                                       202 
#define IM_SWORD_R                                       203 
#define IM_SYSTEM_INFOR_BG_M                             204 
#define IM_TVBOX_LD                                      205 
#define IM_TVBOX_LT                                      206 
#define IM_TVBOX_M                                       207 
#define IM_TVBOX_RD                                      208 
#define IM_TVBOX_RT                                      209 
#define IM_TV_DEL                                        210 
#define IM_TV_FAV                                        211 
#define IM_TV_FAV1                                       212 
#define IM_TV_FAV2                                       213 
#define IM_TV_FAV3                                       214 
#define IM_TV_FAV4                                       215 
#define IM_TV_FAV5                                       216 
#define IM_TV_FAV6                                       217 
#define IM_TV_FAV7                                       218 
#define IM_TV_FAV8                                       219 
#define IM_TV_HIDE                                       220 
#define IM_TV_INFOR                                      221 
#define IM_TV_LOCK                                       222 
#define IM_TV_MOVE                                       223 
#define IM_TV_SELECT                                     224 
#define IM_TV_SKIP                                       225 
#define IM_ZOOM                                          226 
#define IM_ZOOM_ICON_D                                   227 
#define IM_ZOOM_ICON_L                                   228 
#define IM_ZOOM_ICON_R                                   229 
#define IM_ZOOM_ICON_T                                   230 
#define IM_INDEX_LINE                                    231 
#define IM_INPAGE_BANNER_BG_2                            232 
#define IM_KEY_BUTTON                                    233 
#define IM_KEY_BUTTON_F                                  234 
#define IM_KEY_CAP_IC                                    235 
#define IM_KEY_CAP_IC_F                                  236 
#define IM_KEY_IC_BACK                                   237 
#define IM_KEY_IC_DEL                                    238 
#define IM_KEY_IC_FN                                     239 
#define IM_KEY_IC_MENU                                   240 
#define IM_KEY_IC_NEXT                                   241 
#define IM_KEY_IC_REFRESH                                242 
#define IM_KEY_IC_SAVE                                   243 
#define IM_OPENDVB_CTRLBOX_HL                            244 
#define IM_OPENDVB_CTRLBOX_SH                            245 
#define IM_PIC_LOADING_1                                 246 
#define IM_PIC_LOADING_2                                 247 
#define IM_PIC_YOUTUBE_BG                                248 
#define IM_PIC_YOUTUBE_BG_SELECT                         249 
#define IM_PLAY_CONTROL_PAUSE                            250 
#define IM_PLAY_CONTROL_PLAY                             251 
#define IM_POPUPBOX_LD                                   252 
#define IM_POPUPBOX_LT                                   253 
#define IM_POPUPBOX_MD                                   254 
#define IM_POPUPBOX_ML                                   255 
#define IM_POPUPBOX_MM                                   256 
#define IM_POPUPBOX_MR                                   257 
#define IM_POPUPBOX_MT                                   258 
#define IM_POPUPBOX_RD                                   259 
#define IM_POPUPBOX_RT                                   260 
#define IM_SET_BG_DARK                                   261 
#define IM_SET_BG_SIMPLE                                 262 
#define IM_SET_BTN_LEFT_F_LB                             263 
#define IM_SET_BTN_LEFT_F_LM                             264 
#define IM_SET_BTN_LEFT_F_LT                             265 
#define IM_SET_BTN_LEFT_F_MB                             266 
#define IM_SET_BTN_LEFT_F_MM                             267 
#define IM_SET_BTN_LEFT_F_MT                             268 
#define IM_SET_BTN_LEFT_F_RB                             269 
#define IM_SET_BTN_LEFT_F_RM                             270 
#define IM_SET_BTN_LEFT_F_RT                             271 
#define IM_SET_BTN_RIGHT_F_LB                            272 
#define IM_SET_BTN_RIGHT_F_LM                            273 
#define IM_SET_BTN_RIGHT_F_LT                            274 
#define IM_SET_BTN_RIGHT_F_MB                            275 
#define IM_SET_BTN_RIGHT_F_MM                            276 
#define IM_SET_BTN_RIGHT_F_MT                            277 
#define IM_SET_BTN_RIGHT_F_RB                            278 
#define IM_SET_BTN_RIGHT_F_RM                            279 
#define IM_SET_BTN_RIGHT_F_RT                            280 
#define IM_SET_DL_LB                                     281 
#define IM_SET_DL_LM                                     282 
#define IM_SET_DL_LT                                     283 
#define IM_SET_DL_MB                                     284 
#define IM_SET_DL_MM                                     285 
#define IM_SET_DL_MT                                     286 
#define IM_SET_DL_RB                                     287 
#define IM_SET_DL_RM                                     288 
#define IM_SET_DL_RT                                     289 
#define IM_SET_LONG_LINE                                 290 
#define IM_SIGNAL_1                                      291 
#define IM_SIGNAL_2                                      292 
#define IM_SIGNAL_3                                      293 
#define IM_SIGNAL_4                                      294 
#define IM_SIGNAL_5                                      295 
#define IM_USB_INFO                                      296 
#define IM_USB_JUMP                                      297 
#define IM_USB_MODEL                                     298 
#define IM_USB_SET                                       299 
#define IM_VOD_LEFT                                      300 
#define IM_VOD_LINE                                      301 
#define IM_VOD_RIGHT                                     302 
#define IM_VOD_TITLE_1_L                                 303 
#define IM_VOD_TITLE_1_L_S                               304 
#define IM_VOD_TITLE_1_M                                 305 
#define IM_VOD_TITLE_1_M_F                               306 
#define IM_VOD_TITLE_1_M_S                               307 
#define IM_VOD_TITLE_1_R                                 308 
#define IM_VOD_TITLE_1_R_F                               309 
#define IM_VOD_TITLE_1_R_S                               310 
#define IM_VOD_TITLE_L                                   311 
#define IM_VOD_TITLE_L_S                                 312 
#define IM_VOD_TITLE_M                                   313 
#define IM_VOD_TITLE_M_F                                 314 
#define IM_VOD_TITLE_M_S                                 315 
#define IM_VOD_TITLE_R                                   316 
#define IM_VOD_TITLE_R_F                                 317 
#define IM_VOD_TITLE_R_S                                 318 
#define IM_XBTN_PLAY                                     319 
#define IM_XBTN_PLAY_F                                   320 
#define IM_XBTN_RIGHT_F                                  321 
#define IM_XBTN_SET                                      322 
#define IM_XBTN_SET_F                                    323 
#define IM_XBTN_TV                                       324 
#define IM_XBTN_TV_F                                     325 
#define IM_XBTN_VOD                                      326 
#define IM_XBTN_VOD_F                                    327 
#define IM_XICON_SF                                      328 
#define IM_XICON_STOP                                    329 
#define IM_XIC_NO_REPEAT                                 330 
#define IM_XIC_PAUSE                                     331 
#define IM_XIC_PLAY_2                                    332 
#define IM_XIC_PLAY_R                                    333 
#define IM_XIC_PLAY_REPEAT                               334 
#define IM_XIC_SET                                       335 
#define IM_XIC_SET_DEV_DIS                               336 
#define IM_XIC_SET_DEV_SOUND                             337 
#define IM_XIC_SET_NET_LINE                              338 
#define IM_XIC_SET_NET_WIFI                              339 
#define IM_XIC_SET_PER_CA                                340 
#define IM_XIC_SET_PER_LANGUAGE                          341 
#define IM_XIC_SET_PER_LOCK                              342 
#define IM_XIC_SET_SEARCH_ALL                            343 
#define IM_XIC_SET_SEARCH_AUTO                           344 
#define IM_XIC_SET_SEARCH_MANUAL                         345 
#define IM_XIC_SET_SYS_FREQUENCY                         346 
#define IM_XIC_SET_SYS_INFO                              347 
#define IM_XIC_SET_SYS_TIME                              348 
#define IM_XIC_SET_SYS_UPDATE                            349 
#define IM_XIC_TV_MOVE                                   350 
#define IM_XINFORMATION_ICON_6                           351 
#define IM_XINFORMATION_ICON_6_2                         352 
#define IM_XINFORMATION_ICON_7                           353 
#define IM_XINFORMATION_ICON_7_2                         354 
#define IM_XKEY_FN                                       355 
#define IM_XMAIN_BG                                      356 
#define IM_XMEDIO_LEFT_BG                                357 
#define IM_XMEDIO_LEFT_BTN                               358 
#define IM_XMEDIO_LEFT_BTN_F                             359 
#define IM_XMEDIO_LEFT_BTN_LOST                          360 
#define IM_XMEDIO_LEFT_DH_BG                             361 
#define IM_XMEDIO_LEFT_LIST_BG                           362 
#define IM_XMEDIO_LEFT_LIST_F                            363 
#define IM_XMEDIO_LEFT_LIST_X                            364 
#define IM_XMEDIO_LEFT_MUSIC                             365 
#define IM_XMEDIO_LEFT_MUSIC_F                           366 
#define IM_XMEDIO_LEFT_PIC                               367 
#define IM_XMEDIO_LEFT_PIC_F                             368 
#define IM_XMEDIO_LEFT_VEDIO                             369 
#define IM_XMEDIO_LEFT_VEDIO_F                           370 
#define IM_XMEDIO_LIST_BLUE_LB                           371 
#define IM_XMEDIO_LIST_BLUE_LM                           372 
#define IM_XMEDIO_LIST_BLUE_LT                           373 
#define IM_XMEDIO_LIST_BLUE_MB                           374 
#define IM_XMEDIO_LIST_BLUE_MM                           375 
#define IM_XMEDIO_LIST_BLUE_MT                           376 
#define IM_XMEDIO_LIST_BLUE_RB                           377 
#define IM_XMEDIO_LIST_BLUE_RM                           378 
#define IM_XMEDIO_LIST_BLUE_RT                           379 
#define IM_XMEDIO_LIST_YW_LB                             380 
#define IM_XMEDIO_LIST_YW_LM                             381 
#define IM_XMEDIO_LIST_YW_LT                             382 
#define IM_XMEDIO_LIST_YW_MB                             383 
#define IM_XMEDIO_LIST_YW_MM                             384 
#define IM_XMEDIO_LIST_YW_MT                             385 
#define IM_XMEDIO_LIST_YW_RB                             386 
#define IM_XMEDIO_LIST_YW_RM                             387 
#define IM_XMEDIO_LIST_YW_RT                             388 
#define IM_XMUTE_S                                       389 
#define IM_XPLAY_BG                                      390 
#define IM_XPLAY_CTRL_BB                                 391 
#define IM_XPLAY_CTRL_BBB                                392 
#define IM_XPLAY_CTRL_BBB_F                              393 
#define IM_XPLAY_CTRL_BBF                                394 
#define IM_XPLAY_CTRL_BBF_F                              395 
#define IM_XPLAY_CTRL_BB_F                               396 
#define IM_XPLAY_CTRL_BF                                 397 
#define IM_XPLAY_CTRL_BF_F                               398 
#define IM_XPLAY_CTRL_FAV                                399 
#define IM_XPLAY_CTRL_FAV_F                              400 
#define IM_XPLAY_CTRL_ONE                                401 
#define IM_XPLAY_CTRL_ONE_F                              402 
#define IM_XPLAY_CTRL_PLAY                               403 
#define IM_XPLAY_CTRL_PLAY_F                             404 
#define IM_XPLAY_CTRL_PUESH                              405 
#define IM_XPLAY_CTRL_PUESH_F                            406 
#define IM_XPLAY_CTRL_SJ                                 407 
#define IM_XPLAY_CTRL_SJ_F                               408 
#define IM_XPLAY_CTRL_STOP                               409 
#define IM_XPLAY_CTRL_STOP_F                             410 
#define IM_XPLAY_CTRL_XH                                 411 
#define IM_XPLAY_CTRL_XH_F                               412 
#define IM_XPLAY_CTRL_XX                                 413 
#define IM_XPLAY_CTRL_XX_F                               414 
#define IM_XSET_HELP_IC                                  415 
#define IM_XTV_FAV                                       416 
#define IM_XTV_SKIP                                      417 
#define IM_XVOLUME_HORN                                  418 

#endif
