/****************************************************************************

****************************************************************************/
#ifndef __UI_VDO_FAVORITE_H__
#define __UI_VDO_FAVORITE_H__


#define FAVORITE_COMM_ITEM_H 40
/* coordinate */
//title cont
#define VDO_FAVORITE_TITLE_CONTX        90//COMM_ITEM_OX_IN_ROOT 
#define VDO_FAVORITE_TITLE_CONTY        90//40
#define VDO_FAVORITE_TITLE_CONTW        (COMM_BG_W -2*VDO_FAVORITE_TITLE_CONTX) //1040
#define VDO_FAVORITE_TITLE_CONTH        TITLE_H
//BMP
#define VDO_FAVORITE_TITLE_BMPX        (35)  
#define VDO_FAVORITE_TITLE_BMPY        ((VDO_FAVORITE_TITLE_CONTH - VDO_FAVORITE_TITLE_BMPH) >> 1)
#define VDO_FAVORITE_TITLE_BMPW        (50)
#define VDO_FAVORITE_TITLE_BMPH        (50)
//name
#define VDO_FAVORITE_TITLE_TEXTX        (VDO_FAVORITE_TITLE_BMPX + VDO_FAVORITE_TITLE_BMPW + 10)
#define VDO_FAVORITE_TITLE_TEXTY        0
#define VDO_FAVORITE_TITLE_TEXTW        (116)//100
#define VDO_FAVORITE_TITLE_TEXTH        TITLE_H
//botton
#define VDO_FAVORITE_BOTTON_X        VDO_FAVORITE_TITLE_TEXTX + VDO_FAVORITE_TITLE_TEXTW + 10
#define VDO_FAVORITE_BOTTON_Y        (VDO_FAVORITE_TITLE_CONTH - VDO_FAVORITE_BOTTON_H)/2
#define VDO_FAVORITE_BOTTON_W        200
#define VDO_FAVORITE_BOTTON_H        COMM_CTRL_H

#define VDO_FAVORITE_MBOX_TOL          2
#define VDO_FAVORITE_MBOX_COL          2
#define VDO_FAVORITE_MBOX_ROW          1
#define VDO_FAVORITE_MBOX_HGAP         6
#define VDO_FAVORITE_MBOX_VGAP         0
//page
#define VDO_FAVORITE_PAGE_X        VDO_FAVORITE_BOTTON_X + VDO_FAVORITE_BOTTON_W + 400
#define VDO_FAVORITE_PAGE_Y        0
#define VDO_FAVORITE_PAGE_W        100
#define VDO_FAVORITE_PAGE_H        60

#define VDO_FAVORITE_NUM_X        VDO_FAVORITE_PAGE_X + VDO_FAVORITE_PAGE_W
#define VDO_FAVORITE_NUM_Y        0
#define VDO_FAVORITE_NUM_W        100
#define VDO_FAVORITE_NUM_H        60
//list cont
#define VDO_FAVORITE_LIST_CONTX        90//COMM_ITEM_OX_IN_ROOT 
#define VDO_FAVORITE_LIST_CONTY        VDO_FAVORITE_TITLE_CONTY + VDO_FAVORITE_TITLE_CONTH
#define VDO_FAVORITE_LIST_CONTW        VDO_FAVORITE_TITLE_CONTW //1040
#define VDO_FAVORITE_LIST_CONTH        520

#define VDO_FAVORITE_LIST_X        0
#define VDO_FAVORITE_LIST_Y        6
#define VDO_FAVORITE_LIST_W       COMM_ITEM_MAX_WIDTH
#define VDO_FAVORITE_LIST_H       (VDO_FAVORITE_LIST_MID_H + 2 * VDO_FAVORITE_LIST_MID_T) //474

#define VDO_FAVORITE_LIST_MID_L     (20)// 4
#define VDO_FAVORITE_LIST_MID_T     4
#define VDO_FAVORITE_LIST_MID_W   (VDO_FAVORITE_LIST_W - 2 * VDO_FAVORITE_LIST_MID_L)
#define VDO_FAVORITE_LIST_MID_H    ((FAVORITE_COMM_ITEM_H + VDO_FAVORITE_LIST_ITEM_VGAP) * VDO_FAVORITE_LIST_PAGE - VDO_FAVORITE_LIST_ITEM_VGAP)//482

#define VDO_FAVORITE_LIST_ITEM_H        FAVORITE_COMM_ITEM_H
#define VDO_FAVORITE_LIST_ITEM_VGAP    4

#define VDO_FAVORITE_SBAR_X           (VDO_FAVORITE_LIST_X + VDO_FAVORITE_LIST_W - VDO_FAVORITE_SBAR_WIDTH+6)
#define VDO_FAVORITE_SBAR_Y           VDO_FAVORITE_LIST_Y
#define VDO_FAVORITE_SBAR_WIDTH      6
#define VDO_FAVORITE_SBAR_HEIGHT    VDO_FAVORITE_LIST_H

#define VDO_FAVORITE_LIST_BOTTON_X        (VDO_FAVORITE_LIST_CONTW - VDO_FAVORITE_LIST_BOTTON_W - VDO_FAVORITE_LIST_BOTTON_VGAP)
#define VDO_FAVORITE_LIST_BOTTON_Y        (VDO_FAVORITE_LIST_CONTH - VDO_FAVORITE_LIST_BOTTON_H - VDO_FAVORITE_LIST_BOTTON_HGAP)
#define VDO_FAVORITE_LIST_BOTTON_W        100
#define VDO_FAVORITE_LIST_BOTTON_H        COMM_CTRL_H

#define VDO_FAVORITE_LIST_BOTTON_VGAP    12
#define VDO_FAVORITE_LIST_BOTTON_HGAP    4
// help
#define VDO_FAVORITE_HELP_BOTTON_X        90 
#define VDO_FAVORITE_HELP_BOTTON_Y        (VDO_FAVORITE_LIST_CONTY + VDO_FAVORITE_LIST_CONTH + VDO_FAVORITE_LIST_BOTTON_HGAP -40)
#define VDO_FAVORITE_HELP_BOTTON_W        260
#define VDO_FAVORITE_HELP_BOTTON_H        40

#define VDO_FAVORITE_HELP_TEXT_X        (VDO_FAVORITE_HELP_BOTTON_X + VDO_FAVORITE_HELP_BOTTON_W)
#define VDO_FAVORITE_HELP_TEXT_Y        VDO_FAVORITE_HELP_BOTTON_Y
#define VDO_FAVORITE_HELP_TEXT_W        120
#define VDO_FAVORITE_HELP_TEXT_H        44
/* rect style */
#define RSI_VDO_FAVORITE_LIST       RSI_PBACK
/* font style */

/* others */
#define VDO_FAVORITE_LIST_PAGE    10
#define VDO_FAVORITE_LIST_FIELD   2
#define VDO_FAVORITE_BOTTON_NUM   2
#define MAX_VDO_FAVORITE_CNT     100

RET_CODE open_vdo_favorite(u32 para1, u32 para2);

#endif
