/****************************************************************************

 ****************************************************************************/
#ifndef _UI_XUPGRADE_BY_RS232_H_
#define _UI_XUPGRADE_BY_RS232_H_

#include "ui_common.h"

/*! coordinate */
#define XUPGRADE_BY_RS232_X			SYS_LEFT_CONT_W
#define XUPGRADE_BY_RS232_Y			SYS_LEFT_CONT_Y
#define XUPGRADE_BY_RS232_W				SYS_RIGHT_CONT_W
#define XUPGRADE_BY_RS232_H				SYS_LEFT_CONT_H
#define UI_XUPGRADE_BY_RS232_SET_X        60
#define UI_XUPGRADE_BY_RS232_SET_W        (XUPGRADE_BY_RS232_W-2*UI_XUPGRADE_BY_RS232_SET_X)
#define UI_XUPGRADE_BY_RS232_SET_W_L	(UI_XUPGRADE_BY_RS232_SET_W/3)
#define UI_XUPGRADE_BY_RS232_SET_W_R	(UI_XUPGRADE_BY_RS232_SET_W/3*2)

#define XUPGRADE_BY_RS232_ITEM_CNT      5
#define XUPGRADE_BY_RS232_ITEM_X        UI_XUPGRADE_BY_RS232_SET_X
#define XUPGRADE_BY_RS232_ITEM_Y        XUPGRADE_BY_RS232_Y
#define XUPGRADE_BY_RS232_ITEM_LW       UI_XUPGRADE_BY_RS232_SET_W_L
#define XUPGRADE_BY_RS232_ITEM_RW     UI_XUPGRADE_BY_RS232_SET_W_R
#define XUPGRADE_BY_RS232_ITEM_H        COMM_ITEM_H
#define XUPGRADE_BY_RS232_ITEM_V_GAP    20

#define XUPGRADE_BY_RS232_TXT_X	XUPGRADE_BY_RS232_ITEM_X
#define XUPGRADE_BY_RS232_TXT_W	0//60
#define XUPGRADE_BY_RS232_TXT_H	30

#define XUPGRADE_BY_RS232_PBAR_X  (XUPGRADE_BY_RS232_TXT_X + XUPGRADE_BY_RS232_TXT_W)
#define XUPGRADE_BY_RS232_PBAR_W (UI_XUPGRADE_BY_RS232_SET_W - XUPGRADE_BY_RS232_PER_W)
#define XUPGRADE_BY_RS232_PBAR_H  16

#define XUPGRADE_BY_RS232_PER_X (XUPGRADE_BY_RS232_PBAR_X + XUPGRADE_BY_RS232_PBAR_W)
#define XUPGRADE_BY_RS232_PER_W 60
#define XUPGRADE_BY_RS232_PER_H 30

#define XUPGRADE_BY_RS232_MODE_CNT 1// 4 //5

#define XUPGRADE_BY_RS232_TYPE_CNT 2

#define XUPGRADE_BY_RS232_STS_ITEM_CNT 4

/*! rect style */
#define RSI_XUPGRADE_BY_RS232_PBAR_BG     RSI_PROGRESS_BAR_BG
#define RSI_XUPGRADE_BY_RS232_PBAR_MID    RSI_PROGRESS_BAR_MID_YELLOW

/*! font style */

/*! others*/

RET_CODE open_xupgrade_by_rs232(u32 para1, u32 para2);

BOOL ui_is_xrs232_upgrading(void);

#endif
