/****************************************************************************

 ****************************************************************************/
#ifndef __UI_XSTB_HELP_H__
#define __UI_XSTB_HELP_H__

/* coordinate */

#define XSTB_HELP_X			SYS_LEFT_CONT_W
#define XSTB_HELP_Y			SYS_LEFT_CONT_Y
#define XSTB_HELP_W				SYS_RIGHT_CONT_W
#define XSTB_HELP_H				SYS_LEFT_CONT_H

#define XSTB_HELP_VGAP 5
#define XSTB_HELP_INDENTATION 50

#define XSTB_HELP_IC_X         XSTB_HELP_VGAP
#define XSTB_HELP_IC_Y         XSTB_HELP_VGAP
#define XSTB_HELP_IC_W         50
#define XSTB_HELP_IC_H         50

#define XSTB_HELP_TITLE_X         XSTB_HELP_IC_X + XSTB_HELP_IC_W + XSTB_HELP_VGAP
#define XSTB_HELP_TITLE_Y         XSTB_HELP_VGAP
#define XSTB_HELP_TITLE_W         300
#define XSTB_HELP_TITLE_H         XSTB_HELP_IC_H

#define XSTB_HELP_KEY_X         50
#define XSTB_HELP_KEY_Y         XSTB_HELP_IC_Y + XSTB_HELP_IC_H + XSTB_HELP_VGAP
#define XSTB_HELP_KEY_W        (XSTB_HELP_W - XSTB_HELP_KEY_X)/2 - 80
#define XSTB_HELP_KEY_H         25

#define XSTB_HELP_LIST_MID_L     0
#define XSTB_HELP_LIST_MID_T     0
#define XSTB_HELP_LIST_MID_W   0
#define XSTB_HELP_LIST_MID_H    0

#define XSTB_HELP_KEY_LIST_CNT      7
#define XSTB_HELP_KEY_LIST_FIELD   2

#define XSTB_HELP_KEY_LIST_X         XSTB_HELP_KEY_X + XSTB_HELP_INDENTATION
#define XSTB_HELP_KEY_LIST_Y         XSTB_HELP_KEY_Y + XSTB_HELP_KEY_H + XSTB_HELP_VGAP
#define XSTB_HELP_KEY_LIST_W        (XSTB_HELP_W - XSTB_HELP_KEY_LIST_X - XSTB_HELP_INDENTATION)/2
#define XSTB_HELP_KEY_LIST_H         200

#define XSTB_HELP_FN_X         XSTB_HELP_KEY_X
#define XSTB_HELP_FN_Y         XSTB_HELP_KEY_LIST_Y + XSTB_HELP_KEY_LIST_H + XSTB_HELP_VGAP
#define XSTB_HELP_FN_W        (XSTB_HELP_W - XSTB_HELP_FN_X)/2
#define XSTB_HELP_FN_H         25

#define XSTB_HELP_FN_INFO_X         XSTB_HELP_FN_X + XSTB_HELP_INDENTATION
#define XSTB_HELP_FN_INFO_Y         XSTB_HELP_FN_Y + XSTB_HELP_FN_H + XSTB_HELP_VGAP
#define XSTB_HELP_FN_INFO_W        (XSTB_HELP_W - XSTB_HELP_FN_INFO_X- XSTB_HELP_INDENTATION)/2 - 85
#define XSTB_HELP_FN_INFO_H         100

#define XSTB_HELP_NET_X         XSTB_HELP_FN_X
#define XSTB_HELP_NET_Y         XSTB_HELP_FN_INFO_Y + XSTB_HELP_FN_INFO_H + XSTB_HELP_VGAP
#define XSTB_HELP_NET_W        (XSTB_HELP_W - XSTB_HELP_NET_X)/2
#define XSTB_HELP_NET_H         25

#define XSTB_HELP_NET_INFO1_X         XSTB_HELP_NET_X + XSTB_HELP_INDENTATION
#define XSTB_HELP_NET_INFO1_Y         XSTB_HELP_NET_Y + XSTB_HELP_NET_H + XSTB_HELP_VGAP
#define XSTB_HELP_NET_INFO1_W        XSTB_HELP_W - XSTB_HELP_FN_INFO_X- XSTB_HELP_INDENTATION  - 2*XSTB_HELP_INDENTATION
#define XSTB_HELP_NET_INFO1_H         80

#define XSTB_HELP_NET_INFO2_X         XSTB_HELP_NET_X + XSTB_HELP_INDENTATION
#define XSTB_HELP_NET_INFO2_Y         XSTB_HELP_NET_INFO1_Y + XSTB_HELP_NET_INFO1_H + XSTB_HELP_VGAP
#define XSTB_HELP_NET_INFO2_W        XSTB_HELP_W - XSTB_HELP_FN_INFO_X- XSTB_HELP_INDENTATION  - 2*XSTB_HELP_INDENTATION
#define XSTB_HELP_NET_INFO2_H         80

#define XSTB_HELP_SEARCH_X         XSTB_HELP_KEY_X + XSTB_HELP_KEY_W
#define XSTB_HELP_SEARCH_Y         XSTB_HELP_KEY_Y
#define XSTB_HELP_SEARCH_W        (XSTB_HELP_W - XSTB_HELP_NET_X)/2
#define XSTB_HELP_SEARCH_H         25

#define XSTB_HELP_SEARCH_LIST_CNT      3
#define XSTB_HELP_SEARCH_LIST_FIELD   1

#define XSTB_HELP_SEARCH_LIST_X         XSTB_HELP_SEARCH_X + XSTB_HELP_INDENTATION
#define XSTB_HELP_SEARCH_LIST_Y         XSTB_HELP_SEARCH_Y + XSTB_HELP_SEARCH_H + XSTB_HELP_VGAP
#define XSTB_HELP_SEARCH_LIST_W        (XSTB_HELP_W - XSTB_HELP_FN_INFO_X)/2
#define XSTB_HELP_SEARCH_LIST_H         100

#define XSTB_HELP_TIME_SETTING_X         XSTB_HELP_SEARCH_X
#define XSTB_HELP_TIME_SETTING_Y         XSTB_HELP_SEARCH_LIST_Y + XSTB_HELP_SEARCH_LIST_H + XSTB_HELP_VGAP + 40
#define XSTB_HELP_TIME_SETTING_W        (XSTB_HELP_W - XSTB_HELP_NET_X)/2 - XSTB_HELP_INDENTATION
#define XSTB_HELP_TIME_SETTING_H         25

#define XSTB_HELP_TIME_SETTING_INFO1_X         XSTB_HELP_SEARCH_LIST_X
#define XSTB_HELP_TIME_SETTING_INFO1_Y         XSTB_HELP_TIME_SETTING_Y + XSTB_HELP_TIME_SETTING_H + XSTB_HELP_VGAP
#define XSTB_HELP_TIME_SETTING_INFO1_W        (XSTB_HELP_W - XSTB_HELP_FN_INFO_X- XSTB_HELP_INDENTATION)/2- 2*XSTB_HELP_INDENTATION
#define XSTB_HELP_TIME_SETTING_INFO1_H         70

#define XSTB_HELP_TIME_SETTING_INFO2_X         XSTB_HELP_SEARCH_LIST_X
#define XSTB_HELP_TIME_SETTING_INFO2_Y         XSTB_HELP_TIME_SETTING_INFO1_Y + XSTB_HELP_TIME_SETTING_INFO1_H + XSTB_HELP_VGAP
#define XSTB_HELP_TIME_SETTING_INFO2_W        (XSTB_HELP_W - XSTB_HELP_FN_INFO_X- XSTB_HELP_INDENTATION)/2- 2*XSTB_HELP_INDENTATION
#define XSTB_HELP_TIME_SETTING_INFO2_H         80

RET_CODE open_xstbhelp (u32 para1, u32 para2);

#endif

