/****************************************************************************

 ****************************************************************************/
#ifndef _UI_XUPGRADE_BY_USB_H_
#define _UI_XUPGRADE_BY_USB_H_

#include "ui_common.h"

/*! coordinate */

#define XUPGRADE_BY_USB_X			SYS_LEFT_CONT_W
#define XUPGRADE_BY_USB_Y			SYS_LEFT_CONT_Y
#define XUPGRADE_BY_USB_W				SYS_RIGHT_CONT_W
#define XUPGRADE_BY_USB_H				SYS_LEFT_CONT_H
#define UI_XUPGRADE_BY_USB_SET_X        60
#define UI_XUPGRADE_BY_USB_SET_W        (XUPGRADE_BY_USB_W-2*UI_XUPGRADE_BY_USB_SET_X)
#define UI_XUPGRADE_BY_USB_SET_W_L	(UI_XUPGRADE_BY_USB_SET_W/3)
#define UI_XUPGRADE_BY_USB_SET_W_R	(UI_XUPGRADE_BY_USB_SET_W/3*2)

#define XUPGRADE_BY_USB_ITEM_X        UI_XUPGRADE_BY_USB_SET_X
#define XUPGRADE_BY_USB_ITEM_Y        XUPGRADE_BY_USB_Y
#define XUPGRADE_BY_USB_ITEM_LW       UI_XUPGRADE_BY_USB_SET_W_L
#define XUPGRADE_BY_USB_ITEM_RW      UI_XUPGRADE_BY_USB_SET_W_R
#define XUPGRADE_BY_USB_ITEM_H        50//COMM_ITEM_H
#define XUPGRADE_BY_USB_ITEM_V_GAP    16

#define XUPGRADE_BY_USB_TXT_X	XUPGRADE_BY_USB_ITEM_X
#define XUPGRADE_BY_USB_TXT_W	0//60
#define XUPGRADE_BY_USB_TXT_H	30

#define XUPGRADE_BY_USB_PBAR_X  (XUPGRADE_BY_USB_TXT_X + XUPGRADE_BY_USB_TXT_W)
#define XUPGRADE_BY_USB_PBAR_W (UI_XUPGRADE_BY_USB_SET_W - XUPGRADE_BY_USB_PER_W)
#define XUPGRADE_BY_USB_PBAR_H  16

#define XUPGRADE_BY_USB_PER_X (XUPGRADE_BY_USB_PBAR_X + XUPGRADE_BY_USB_PBAR_W)
#define XUPGRADE_BY_USB_PER_W 60
#define XUPGRADE_BY_USB_PER_H 30

#define XUPGRADE_BY_USB_LIST_X	240 + XUPGRADE_BY_USB_X
#define XUPGRADE_BY_USB_LIST_Y      300 + XUPGRADE_BY_USB_Y
#define XUPGRADE_BY_USB_LIST_W	300
#define XUPGRADE_BY_USB_LIST_H	260

#define XUPGRADE_BY_USB_LIST_MIDL  0
#define XUPGRADE_BY_USB_LIST_MIDT  0
#define XUPGRADE_BY_USB_LIST_MIDW  (XUPGRADE_BY_USB_LIST_W - 2 * XUPGRADE_BY_USB_LIST_MIDL)
#define XUPGRADE_BY_USB_LIST_MIDH  (XUPGRADE_BY_USB_LIST_H - 2 * XUPGRADE_BY_USB_LIST_MIDT)

#define XUPGRADE_DLG_X   ((1280 -XUPGRADE_DLG_W)/2)
#define XUPGRADE_DLG_Y   ((720-XUPGRADE_DLG_H)/2)
#define XUPGRADE_DLG_W   300
#define XUPGRADE_DLG_H    200


#define XUPGRADE_BY_USB_LIST_VGAP  0

#define XUPGRADE_BY_USB_LIST_PAGE     7
#define XUPGRADE_BY_USB_LIST_FIELD    1



#define XUPGRADE_BY_USB_MODE_CNT 2
#define XUPGRADE_BY_USB_MAXMODE_CNT 3

#define XUPGRADE_BY_USB_MAX_MISC_FILES_CNT 7


#define XUPGRADE_BY_USB_STS_ITEM_CNT 1  //  4

/*! rect style */
#define RSI_XUPGRADE_BY_USB_PBAR_BG     RSI_PROGRESS_BAR_BG
#define RSI_XUPGRADE_BY_USB_PBAR_MID    RSI_PROGRESS_BAR_MID_YELLOW

/*! font style */

/*! others*/
#define XSTS_STR_MAX_LEN       32
#define XVERSION_LIST_CNT 2//4
#define XVERSION_LIST_FIELD 3
typedef enum
{
  XUPG_MODE_IMG,
  XUPG_MODE_MISC
}xupgrade_mode_t;

typedef enum
{
    UI_XUSB_UPG_IDEL,
    UI_XUSB_UPG_LOADING,
    UI_XUSB_UPG_LOAD_END,
    UI_XUSB_UPG_BURNING
}ui_xusb_upg_status_t;
RET_CODE open_xupgrade_by_usb(u32 para1, u32 para2);

u32 ui_xusb_upgade_sts(void);

#endif
