/****************************************************************************

 ****************************************************************************/
#ifndef __UI_XBOOT_WIZARD_H__
#define __UI_XBOOT_WIZARD_H__

/* coordinate */

#define XBOOT_WIZARD_X			0
#define XBOOT_WIZARD_Y			0
#define XBOOT_WIZARD_W		1280
#define XBOOT_WIZARD_H			720

#define XBOOT_WIZARD_TITLE_X   0
#define XBOOT_WIZARD_TITLE_Y   5
#define XBOOT_WIZARD_TITLE_W   XBOOT_WIZARD_W
#define XBOOT_WIZARD_TITLE_H   80

#define XBOOT_WIZARD_BMP_X   0
#define XBOOT_WIZARD_BMP_Y   XBOOT_WIZARD_TITLE_Y + XBOOT_WIZARD_TITLE_H + 15
#define XBOOT_WIZARD_BMP_W   XBOOT_WIZARD_W
#define XBOOT_WIZARD_BMP_H   500

#define XBOOT_WIZARD_BOX_CON_X   50 - 16/2 + 100
#define XBOOT_WIZARD_BOX_CON_Y   XBOOT_WIZARD_BMP_Y + XBOOT_WIZARD_BMP_H + 20
#define XBOOT_WIZARD_BOX_CON_W   XBOOT_WIZARD_BOX_BTN_W + 16
#define XBOOT_WIZARD_BOX_CON_H     XBOOT_WIZARD_BOX_BTN_H + 16

#define XBOOT_WIZARD_BOX_BTN_X   8
#define XBOOT_WIZARD_BOX_BTN_Y   8
#define XBOOT_WIZARD_BOX_BTN_W   43
#define XBOOT_WIZARD_BOX_BTN_H   34

#define XBOOT_WIZARD_BOX_TXET_X   XBOOT_WIZARD_BOX_CON_X + XBOOT_WIZARD_BOX_CON_W +10
#define XBOOT_WIZARD_BOX_TXET_Y   XBOOT_WIZARD_BOX_CON_Y + (50 - XBOOT_WIZARD_BOX_TXET_H)/2
#define XBOOT_WIZARD_BOX_TXET_W   350 - XBOOT_WIZARD_BOX_TXET_X - 20
#define XBOOT_WIZARD_BOX_TXET_H   50

#define XBOOT_WIZARD_NEXTBTN_X   1000
#define XBOOT_WIZARD_NEXTBTN_Y   XBOOT_WIZARD_BOX_CON_Y
#define XBOOT_WIZARD_NEXTBTN_W   70
#define XBOOT_WIZARD_NEXTBTN_H   50

#define XBOOT_WIZARD_NEXTBTNTXET_X   XBOOT_WIZARD_NEXTBTN_X + XBOOT_WIZARD_NEXTBTN_W +10
#define XBOOT_WIZARD_NEXTBTNTXET_Y   XBOOT_WIZARD_BOX_CON_Y+(XBOOT_WIZARD_BOX_CON_H - XBOOT_WIZARD_BOX_TXET_H)/2
#define XBOOT_WIZARD_NEXTBTNTXET_W   150
#define XBOOT_WIZARD_NEXTBTNTXET_H   50

#define XBOOT_WIZARD_PWDLG_W             390// 342
#define XBOOT_WIZARD_PWDLG_H              160

#define XBOOT_WIZARD_ASK_L (1280 - XBOOT_WIZARD_PWDLG_W)/2
#define XBOOT_WIZARD_ASK_T (720 - XBOOT_WIZARD_PWDLG_H)/2
#define XBOOT_WIZARD_ASK_R (XBOOT_WIZARD_ASK_L + XBOOT_WIZARD_PWDLG_W)
#define XBOOT_WIZARD_ASK_B (XBOOT_WIZARD_ASK_T + XBOOT_WIZARD_PWDLG_H)



RET_CODE open_xbootWizard (u32 para1, u32 para2);

#endif

